import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
  agent { label 'principal' }
  environment {
    appName = "variable" 
  }
  stages {
    stage("paso 1") {
      steps {
        script {			
          bat "cd C:/Users/alumno/Desktop/copia de seguridad && javac prueba.java"
        }
      }
    }
    stage("paso 2") {
      steps {
        script {			
          bat "java -classpath C:/Users/alumno/Desktop/copia de seguridad prueba"
        }
      }
    }
    stage("paso 3") {
      steps {
        script {			
          echo "_____________________"
          echo "exitoso"
          echo "____________"
        }
      }
    }
  }
}
