import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
  agent { label 'principal' }
  environment {
    appName = "variable" 
  }
  stages {
    stage("paso 1") {
      steps {
        script {			
          bat "cd C:/Users/alumno/Desktop/copia && javac prueba.java"
        }
      }
    }
    stage("paso 2") {
      steps {
        script {			
          def command = "java -cp C:/Users/alumno/Desktop/copia prueba"
          def process = command.execute()
          process.waitFor()
          println process.text
        }
      }
    }
    stage("paso 3") {
      steps {
        script {			
          echo "_____________________"
          echo "exitoso"
          echo "_____________________"
        }
      }
    }
  }
}

